package te.application.appConstants;

import te.application.utilities.Utils;

public class bearerToken {
    public static String ALFUTTAIM = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55IjoiYWZyIiwiYXBpX3Rva2VuIjoiODQ5MmZjNDgtNDQ0OS00MWMyLWFjZDMtZGJiMWVhQUYiLCJzZXNzaW9uX3Rva2VuIjoiMTM0MDVlNjgtYzc1OC00MDQ1LTlmYzAtZmIxZGZjODE0ZGNhIn0.FFCYIvfo3u3YUYomwNoKs1ye9A7mmU_ijVBU5PD96Cs";
    public static String FNB = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55IjoiZW50ZXJ0YWluZXIiLCJhcGlfdG9rZW4iOiIyNGZlOThiNC05ZjFjLTRjYjgtOGFhNC0zMWY1YWMwNmMyNmIiLCJzZXNzaW9uX3Rva2VuIjoiNzFjZDczNjgtNmYxMy00YzVlLThjZGQtYjkzMjIxMzdlY2ExIn0.qdinslzvXb79GBZObPSH8rG4cL8utB_jsMFMsQhkSio";


    //Basic cWx6ZnFnaHBrZWl3aG16ZzprJFZ9QiooNkRLNXltVE5iSD80PHJqM3VHRjtbfnQ+cQ==
    public static String B2C = "QmFzaWMgY1d4NlpuRm5hSEJyWldsM2FHMTZaenBySkZaOVFpb29Oa1JMTlhsdFZFNWlTRDgwUEhKcU0zVkhSanRiZm5RK2NRPT0=";


}
